# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-11 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_auto_20160611_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
